In [3]:
# ML can be used for diagnosis of disease as well

from __future__ import print_function, division
from future.utils import iteritems
from builtins import range,input

#install future pip install future

#numpy incase we need it
import numpy as np

#import function that will get the data
#yes, sklearn comes with built-in datasets

from sklearn.datasets import load_breast_cancer

#load the data
data = load_breast_cancer()

print(type(data))

#note : it is a Bunch object
#this basically acts like a dictionary where you can treat the keys like attributes
data.keys()
print(data.keys())

# 'data' (the attribute) means the input
print(data.data)
print(data.data.shape)

#it has 569 samples, 30 features

#'target' attributes
print(data.target)
#note how the targets are just 0s and 1s
#normally, when you have k targets, they are labeled 0..K-1

#their meaning is not lost
print(data.target_names)

#there are also 569 corresponding targets
print(data.data.shape)

#you can also determine the meaning of each feature
print(data.feature_names)

#normally we would put all of our imports at the top
#but  this lets us tell a story
from sklearn.model_selection import train_test_split


#split the data into train and test sets
#this lets us simulate how our model will perform in future

X_train, X_test, y_train, y_test = train_test_split(data.data, data.target, test_size = 0.33)

#instantiate a classifier and train it
from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier()
model.fit(X_train,y_train)

#evaluate the model's perfomance
print(model.score(X_train, y_train))
print(model.score(X_test, y_test))

#how to make predictions
predictions = model.predict(X_test)

#what we get?
predictions

#manually check the accuracy of your predictions
N=len(y_test)
print(predictions==y_test)
np.sum(predictions == y_test)/N 
print(np.sum(predictions == y_test)/N)#can also just call np.mean()

# we can use deep learning to solve the same probkem!

from sklearn.neural_network import MLPClassifier

#you will see why scaling is needed in a later course
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_train2 = scaler.fit_transform(X_train)
X_test2 = scaler.fit_transform(X_test)

model = MLPClassifier(max_iter=500)
#earlier we got a warning that the training hadn't converged, so let's make it train longer
#Lesson to remember : Deep learning is not a "plug and play" type of algorithm
model.fit(X_train2,y_train)

#evaluate the model's perfomance
model.score(X_train2,y_train)
model.score(X_test2,y_test)

<class 'sklearn.utils._bunch.Bunch'>
dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])
[[1.799e+01 1.038e+01 1.228e+02 ... 2.654e-01 4.601e-01 1.189e-01]
 [2.057e+01 1.777e+01 1.329e+02 ... 1.860e-01 2.750e-01 8.902e-02]
 [1.969e+01 2.125e+01 1.300e+02 ... 2.430e-01 3.613e-01 8.758e-02]
 ...
 [1.660e+01 2.808e+01 1.083e+02 ... 1.418e-01 2.218e-01 7.820e-02]
 [2.060e+01 2.933e+01 1.401e+02 ... 2.650e-01 4.087e-01 1.240e-01]
 [7.760e+00 2.454e+01 4.792e+01 ... 0.000e+00 2.871e-01 7.039e-02]]
(569, 30)
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 1 0 0 0 0 0 0 0 0 1 0 1 1 1 1 1 0 0 1 0 0 1 1 1 1 0 1 0 0 1 1 1 1 0 1 0 0
 1 0 1 0 0 1 1 1 0 0 1 0 0 0 1 1 1 0 1 1 0 0 1 1 1 0 0 1 1 1 1 0 1 1 0 1 1
 1 1 1 1 1 1 0 0 0 1 0 0 1 1 1 0 0 1 0 1 0 0 1 0 0 1 1 0 1 1 0 1 1 1 1 0 1
 1 1 1 1 1 1 1 1 0 1 1 1 1 0 0 1 0 1 1 0 0 1 1 0 0 1 1 1 1 0 1 1 0 0 0 1 0
 1 0 1 1 1 0 1 1 0 0 1 0 0 0 0 1 0 0 0 1 0 1 0 1 1 0 1 0 0 0 0

0.9840425531914894